# Generated by Django 4.2 on 2025-02-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive_tests_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mood',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Эмоциональное состояние'),
        ),
    ]
